name: deploy to dev
run-name: 🚀 | Deploy Dev Pipeline | ${{ github.actor }}
on:
  push

jobs:
  # Should we run anything else before deploying?

  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install python dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: deploy to dev
        run: |
          python main.py mock-deploy --host https://dev.example.com --token 99b1ff8f11781541f7f89f9bd41c4a17